server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring:
      jpa:
        hibernate:
          ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
#      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jackson:
    default-property-inclusion: non_null

coindesk:
  api:
    url: https://kengp3.github.io/blog/coindesk.json